12.0 pull request (TA#15981)
Numigi/odoo-git-addons pull request #1
Opened 2019-11-13 19:51 UTC by foutoucour

https://isidor.numigi.net/web?debug=1#id=15981&action=298&model=project.task&view_type=form&menu_id=200

2019-11-13 21:59 UTC, foutoucour commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- github_pull_request/models/github_pull_request.py  2
- github_pull_request_project/models/github_pull_request.py  2
- github_pull_request_project/tests/test_project_task.py  2
- github_pull_request/tests/test_github_pull_request.py  5
         

Clones added
============
- github_pull_request/tests/test_github_pull_request.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/odoo-git-addons/odoo-git-addons/pullRequest?prid=4495225&bid=15157802)

2019-11-13 22:11 UTC, foutoucour commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Coverage increased per file
===========================
+ github_pull_request_project/models/github_pull_request.py  80
+ github_pull_request/models/github_pull_request.py  100
+ github_pull_request_project/tests/test_project_task.py  100
+ github_pull_request/tests/test_github_pull_request.py  100
         

Complexity increasing per file
==============================
- github_pull_request_project/models/github_pull_request.py  2
- github_pull_request/models/github_pull_request.py  2
- github_pull_request_project/tests/test_project_task.py  2
- github_pull_request/tests/test_github_pull_request.py  5
         

Clones added
============
- github_pull_request/tests/test_github_pull_request.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/odoo-git-addons/odoo-git-addons/pullRequest?prid=4495225&bid=15157802)

2019-11-14 15:34 UTC, ddufresne requested changes

2019-11-14 15:34 UTC, ddufresne commented on github_pull_request/__manifest__.py
> +        'views/ir_ui_view.xml',
@foutoucour peux-tu renommer le fichier pour views/github_pull_request.xml ?

Si d'autres modèles s'ajoutent éventuellement, on aura un fichier par modèle.

2019-11-14 15:34 UTC, ddufresne commented on github_pull_request/models/github_pull_request.py
> +            vals.update(res.groupdict())
Ces 4 lignes sont presque pareilles à celles de la méthode create.
Elles peuvent être regrouppées dans une fonction.

2019-11-14 15:34 UTC, ddufresne commented on github_pull_request/tests/test_github_pull_request.py
> +            }
@foutoucour personnellement, je préfère tester un seul champ par fonction de test.

J'aimerais qu'on en discute, car, là, j'allais écrire un paragraphe ;)

2019-11-14 15:34 UTC, ddufresne commented on github_pull_request_project/models/github_pull_request.py
> +def evaluate_pull_request_states(task):
Cette fonction retourne True si aucun PR est ouvert.

Ne devrait-elle pas s'appeller evaluate_no_open_pull_request ?

2019-11-14 15:34 UTC, ddufresne commented on github_pull_request_project/models/github_pull_request.py
> +    overall_pull_request_state = fields.Boolean(
Le nom du champ indique qu'il s'agit d'un état alors qu'il s'agit d'un booléen.

Généralement, un état est représenté par un champ Sélection.

Le nom du champ pourrait être no_open_pull_request.

2019-11-14 15:34 UTC, ddufresne commented on github_pull_request_project/models/github_pull_request.py
> +            record.all_pull_request_ready = evaluate_pull_request_states(record)
ce champ n'est pas défini il me semble.

2019-11-14 15:34 UTC, ddufresne commented on github_pull_request_project/__manifest__.py
> +        'views/ir_ui_view.xml',
même chose ici, le nom du fichier devrait être le nom du modèle.

2019-11-14 15:34 UTC, ddufresne commented on github_pull_request_project/views/ir_ui_view.xml
> +            <xpath expr="//div[@class='oe_button_box']" position="inside">
``<div name="button_box" position="inside">``

2019-11-14 15:34 UTC, ddufresne commented on github_pull_request_project/views/ir_ui_view.xml
> +            <xpath expr="//field[@name='user_id']" position="after">
``<field name="user_id" position="after">``

2019-11-14 15:34 UTC, ddufresne commented on github_pull_request_project/views/ir_ui_view.xml
> +                <xpath expr="//field[@name='stage_id']" position="after">
même chose

2019-11-14 15:34 UTC, ddufresne commented on github_pull_request_project/views/ir_ui_view.xml
> +        <field name="type">form</field>
non nécessaire

2019-11-14 15:34 UTC, ddufresne commented on github_pull_request_project/views/ir_ui_view.xml
> +        <field name="arch" type="xml">
non nécessaier

2019-11-14 15:34 UTC, ddufresne commented on github_pull_request_project/views/ir_ui_view.xml
> +            <data>
``<data>`` n'est pas requis

2019-11-14 19:49 UTC, foutoucour commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           

Complexity increasing per file
==============================
- github_pull_request/models/github_pull_request.py  2
- github_pull_request_project/tests/test_project_task.py  2
- github_pull_request/tests/test_github_pull_request.py  2
- github_pull_request_project/models/github_pull_request.py  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/odoo-git-addons/odoo-git-addons/pullRequest?prid=4495225&bid=15157802)

2019-11-14 19:58 UTC, foutoucour commented on github_pull_request/tests/test_github_pull_request.py
> +            }
haha @ddufresne.
pas besoin j'ai compris l'intention. Je pense que la mise à jour va te plaire ;)

2019-11-14 19:59 UTC, foutoucour commented
@ddufresne mise à jour du code. Merci pour les commentaires

2019-11-14 19:59 UTC, foutoucour commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           

Complexity increasing per file
==============================
- github_pull_request_project/models/github_pull_request.py  3
- github_pull_request/models/github_pull_request.py  2
- github_pull_request/tests/test_github_pull_request.py  2
- github_pull_request_project/tests/test_project_task.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/odoo-git-addons/odoo-git-addons/pullRequest?prid=4495225&bid=15157802)

2019-11-14 20:01 UTC, foutoucour commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- github_pull_request/models/github_pull_request.py  2
- github_pull_request_project/tests/test_project_task.py  2
- github_pull_request/tests/test_github_pull_request.py  2
- github_pull_request_project/models/github_pull_request.py  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/odoo-git-addons/odoo-git-addons/pullRequest?prid=4495225&bid=15157802)

2019-11-14 20:16 UTC, ddufresne commented on github_pull_request/tests/test_github_pull_request.py
> +            }
@foutoucour ah oui, c'est le jour et la nuit. Super travail.

2019-11-14 20:25 UTC, ddufresne approved these changes

2019-11-14 20:25 UTC, ddufresne commented
@foutoucour merci pour les améliorations ;)

2019-11-14 20:26 UTC, merged