GitHub pr controller
Numigi/odoo-git-addons pull request #4
Opened 2019-11-18 20:19 UTC by ddufresne

https://www.numigi.com/web#id=15985&action=292&active_id=600&model=project.task&view_type=form&menu_id=200

2019-11-18 20:22 UTC, foutoucour commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           

Complexity increasing per file
==============================
- github_pull_request/controllers/github.py  3
- github_pull_request/models/github_event.py  1
- github_pull_request/tests/test_github_controller.py  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/odoo-git-addons/odoo-git-addons/pullRequest?prid=4520787&bid=15226992)

2019-11-18 20:27 UTC, foutoucour commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           

Complexity increasing per file
==============================
- github_pull_request/tests/test_github_controller.py  4
- github_pull_request/controllers/github.py  3
- github_pull_request/models/github_event.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/odoo-git-addons/odoo-git-addons/pullRequest?prid=4520787&bid=15226992)

2019-11-18 20:28 UTC, ddufresne commented
depends on https://github.com/Numigi/odoo-base-addons/pull/42

2019-11-18 21:51 UTC, foutoucour requested changes

2019-11-18 21:51 UTC, foutoucour commented on github_pull_request/controllers/github.py
> +    if GITHUB_TOKEN_HEADER not in headers:
est que `headers.get(GITHUB_TOKEN_HEADER, "")` ne marchait pas ?

2019-11-18 21:51 UTC, foutoucour commented on github_pull_request/controllers/github.py
> +        return None
la signature dit que la fonction retourne une string. Je verrai plus à mettre `""` du coup.
Est ce qu'il y a une raison pour le None ?

2019-11-18 21:51 UTC, foutoucour commented on github_pull_request/controllers/github.py
> +    @http.route('/web/github/event', type='json', auth='none', sitemap=False)
J'ai l'impression que le module https://github.com/OCA/server-auth pourrait être intéressant ici.
J'aime beaucoup de fait que la clé soit dans la config, ce qui éviterai de faire un changement dans updoo.
Qu'est ce que tu en dis ?

2019-11-18 21:59 UTC, ddufresne commented on github_pull_request/controllers/github.py
> +    @http.route('/web/github/event', type='json', auth='none', sitemap=False)
bon point. 

Toutefois, ce qu'on a besoin, c'est seulement server_environment:

https://github.com/OCA/server-env/tree/12.0/server_environment

2019-11-18 22:00 UTC, ddufresne commented on github_pull_request/controllers/github.py
> +    if GITHUB_TOKEN_HEADER not in headers:
@foutoucour il y avait une raison au départ. Mais plus maintenant. Je  vais simplifier.

2019-11-18 22:10 UTC, foutoucour commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           

Complexity increasing per file
==============================
- github_pull_request/tests/test_github_controller.py  4
- github_pull_request/models/github_event.py  1
- github_pull_request/controllers/github.py  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/odoo-git-addons/odoo-git-addons/pullRequest?prid=4520787&bid=15226992)

2019-11-20 15:33 UTC, foutoucour commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Coverage increased per file
===========================
+ github_pull_request/models/github_event.py  100
+ github_pull_request/controllers/github.py  100
+ github_pull_request/tests/test_github_controller.py  100
+ github_pull_request/controllers/__init__.py  100
         

Complexity increasing per file
==============================
- github_pull_request/models/github_event.py  1
- github_pull_request/controllers/github.py  3
- github_pull_request/tests/test_github_controller.py  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/odoo-git-addons/odoo-git-addons/pullRequest?prid=4520787&bid=15226992)

2019-11-20 15:39 UTC, merged