Add processing of github events
Numigi/odoo-git-addons pull request #7
Opened 2019-12-03 15:11 UTC by ddufresne

https://www.numigi.com/web#id=15985&action=292&active_id=600&model=project.task&view_type=form&menu_id=200

2019-12-03 15:15 UTC, foutoucour commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Coverage increased per file
===========================
+ github_pull_request/controllers/github.py  100
+ github_pull_request/tests/test_github_controller.py  100
+ github_pull_request_project/tests/test_project_task.py  100
+ github_pull_request/controllers/__init__.py  100
+ github_pull_request/models/common.py  100
+ github_pull_request/models/github_pull_request.py  100
+ github_pull_request/tests/test_github_pull_request.py  100
+ github_pull_request/tests/test_github_event.py  100
+ github_pull_request/models/github_event.py  98
+ github_pull_request_project/models/github_pull_request.py  89
         

Complexity increasing per file
==============================
- github_pull_request/tests/test_github_event.py  3
- github_pull_request/models/github_event.py  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/odoo-git-addons/odoo-git-addons/pullRequest?prid=4607647&bid=15458791)

2019-12-03 15:29 UTC, foutoucour commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Coverage increased per file
===========================
+ github_pull_request_project/tests/test_project_task.py  100
+ github_pull_request/controllers/__init__.py  100
+ github_pull_request/controllers/github.py  100
+ github_pull_request/tests/test_github_controller.py  100
+ github_pull_request_project/models/github_pull_request.py  89
+ github_pull_request/models/github_event.py  98
+ github_pull_request/models/common.py  100
+ github_pull_request/tests/test_github_event.py  100
+ github_pull_request/tests/test_github_pull_request.py  100
+ github_pull_request/models/github_pull_request.py  100
         

Complexity increasing per file
==============================
- github_pull_request/models/github_event.py  3
- github_pull_request/tests/test_github_event.py  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/odoo-git-addons/odoo-git-addons/pullRequest?prid=4607647&bid=15458791)

2019-12-03 15:58 UTC, foutoucour requested changes
Pas mal de commentaire. Book moi un point demain si tu veux en discuter.

2019-12-03 15:58 UTC, foutoucour commented on github_pull_request/README.rst
> +This modules defines GitHub pull requests and events.
ce titre me fait dire que nous parlons de deux modules différents ici.
Quelqu'un pourrait avoir besoin de la définition d'une pull request Github sans vouloir les events.
C'était notre cas d'ailleurs. Nous voulions définir les PRs sans toute la poutine des autres modules.

2019-12-03 15:58 UTC, foutoucour commented on github_pull_request/README.rst
> +As system administrator, I go to ``Configuration > Technical > GitHub > Events``.
Ce menu me confirme mon sentiment que ça devrait être dans un autre module

2019-12-03 15:58 UTC, foutoucour commented on github_pull_request/README.rst
> +Github Webhook
Je me pose la question aussi pour le webhook du coup :(

2019-12-03 15:58 UTC, foutoucour commented on github_pull_request/models/github_pull_request.py
> +    latest_update = fields.Datetime()
Ce champs devrait faire parti du scope de `GithubPullRequestWithEvents`

2019-12-03 15:58 UTC, foutoucour commented on github_pull_request/models/github_pull_request.py
> +    title = fields.Char()
Ce champs devrait faire parti du scope de `GithubPullRequestWithEvents`

2019-12-03 15:58 UTC, foutoucour commented on github_pull_request/tests/test_github_event.py
> +    def _read_payload(self, filename):
👍

2019-12-03 15:58 UTC, foutoucour commented on github_pull_request/tests/test_github_event.py
> +class TestGithubEvent(common.SavepointCase):
Il manquerai le test pour l'assignation du champ `title`

2019-12-03 15:58 UTC, foutoucour commented on github_pull_request/tests/test_github_event.py
> +class TestGithubEvent(common.SavepointCase):
Il manquerait aussi le test du comportement d'un retry d'un même job.

2019-12-03 15:58 UTC, foutoucour commented on github_pull_request/views/github_pull_request.xml
> +            <field name="title"/>
est ce que la vue liste ne devrait pas être mise à jour aussi pour mettre en avant le titre aussi ?

2019-12-04 19:35 UTC, ddufresne commented on github_pull_request/tests/test_github_event.py
> +class TestGithubEvent(common.SavepointCase):
done

2019-12-04 19:36 UTC, ddufresne commented on github_pull_request/views/github_pull_request.xml
> +            <field name="title"/>
done

2019-12-04 19:36 UTC, ddufresne commented on github_pull_request/tests/test_github_event.py
> +class TestGithubEvent(common.SavepointCase):
done

2019-12-04 19:38 UTC, ddufresne commented on github_pull_request/models/github_pull_request.py
> +    title = fields.Char()
plus ou moins, le titre n'est pas lié à la notion d'événement.

2019-12-04 19:38 UTC, ddufresne commented on github_pull_request/models/github_pull_request.py
> +    latest_update = fields.Datetime()
oui

2019-12-04 19:41 UTC, foutoucour commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 3
           

Complexity increasing per file
==============================
- github_event/tests/test_github_event.py  2
- github_event/models/github_event.py  4
- github_event_webhook/tests/test_github_controller.py  4
- github_event/tests/common.py  2
- github_event_webhook/controllers/github.py  3
- github_pull_request/tests/test_github_event.py  3
- github_pull_request/models/github_event.py  2
- github_event_webhook/models/github_event.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/odoo-git-addons/odoo-git-addons/pullRequest?prid=4607647&bid=15458791)

2019-12-04 19:42 UTC, foutoucour commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- github_event/models/github_event.py  4
- github_event_webhook/controllers/github.py  3
- github_event/tests/test_github_event.py  2
- github_event_webhook/models/github_event.py  1
- github_event/tests/common.py  2
- github_event_webhook/tests/test_github_controller.py  4
- github_pull_request/tests/test_github_event.py  3
- github_pull_request/models/github_event.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/odoo-git-addons/odoo-git-addons/pullRequest?prid=4607647&bid=15458791)

2019-12-04 22:22 UTC, foutoucour commented on github_pull_request/models/github_pull_request.py
> +    title = fields.Char()
Tu as raison. Ton approche est mieux

2019-12-04 22:29 UTC, foutoucour approved these changes
👍

2019-12-05 12:25 UTC, merged